---
- name: Install Slack
  aur:
    name: slack-desktop
    user: {{user.name}}
  tags:
    - aur
    - work

- name: Install development environment: Kubernetes
  pacman:
    name: docker
    state: present
  tags:
    - go
    - work
- name: Install development environment (AUR): Kubernetes
  aur:
    name: kubectl-bin,minikube
    user: {{user.name}}
  tags:
    - aur
    - go
    - work

- name: Install Chromium
  pacman:
    name: chromium
    state: present
  tags:
    - work
